import type { Metadata } from "next";
import { oswald } from "@/app/fonts";
import "./globals.css";
import { PropsWithChildren } from "react";
import PageWrapper from "@/components/common/PageWrapper";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { hasRole } from "@/lib/services/role";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: PropsWithChildren) {
  const lang = await getLocale();
  const messages = await getMessages();

  const doesRoleExist = hasRole();

  return (
    <html className="w-full h-full" lang={lang}>
      <body className={`bg-1 p-4 h-full relative ${oswald.className}`}>
        <NextIntlClientProvider messages={messages}>
          {doesRoleExist ? <PageWrapper>{children}</PageWrapper> : children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
